version: "3.8"

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: enttest
      MYSQL_USER: enter
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3336:3306"
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d:ro
      - db_volume:/var/lib/mysql:delegated
  backend:
    build: .
    environment:
      WAIT_HOSTS: db:3306
      APP_PORT: 8080
      APP_DB_HOST: db
      APP_DB_PORT: 3306
      APP_DB_DATABASE: enttest
      APP_DB_USER: enter
      APP_DB_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  db_volume:
    driver: local
